### ISSUE TITLE
Lauuch with crashes everywhere in any time I click any buttons

### ISSUE THREAD

**Issue by Robin-Rhee** [Sunnyyoung/AppleReserver#2]
Lauuch with crashes everywhere in any time I click any buttons

![35340ef7-ae9b-45f1-b592-27eb1e9acb40](https://cloud.githubusercontent.com/assets/3489980/18946025/b5c7e2cc-865f-11e6-958f-8ca540564640.png)

![37f65465-55aa-4083-b8a4-adb393aad6a3](https://cloud.githubusercontent.com/assets/3489980/18945935/4621ab9c-865f-11e6-9295-4ca9beb7c43e.png)

**Comment by sunnyyoung** [comment]
太少信息了，添加个`All Exceptions`断点看看

**Comment by Robin-Rhee** [comment]
I couldn't retrieve the whole of project since the GFW hinder me from reaching cocoapods.
So I'd got to do some own workarounds for orignal codes to get used to packets I had rounded up.
What's relieved is it worked out at last.
Here are some key codes:

-(void)loadStoreAndDevice {
    self.deviceDictionary = [Device deviceDictionary];
    NSString *url = @"https://reserve.cdn-apple.com/CN/zh_CN/reserve/iPhone/stores.json";
    NSURLSessionDataTask *task = [[NSURLSession sharedSession] dataTaskWithURL:[NSURL URLWithString:url] completionHandler:^(NSData \* _Nullable data, NSURLResponse \* _Nullable response, NSError \* _Nullable error) {
        //Failed
        if (error) {
            return;
        }
        NSDictionary *result = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingAllowFragments error:nil];
        if (![result isKindOfClass:[NSDictionary class]]) {
            return;
        }  
        //Succeeded
        dispatch_async(dispatch_get_main_queue(), ^{
            self.storeArray = [Store objectArrayWithKeyValuesArray:result[@"stores"]];
            [self.storeTableView reloadData];
        });
    }];
    [task resume];
}

-(void)reloadAvailability {
    NSString *url = [NSString stringWithFormat:@"https://reserve.cdn-apple.com/CN/zh_CN/reserve/iPhone/availability.json"];
    NSURLSessionDataTask *task = [[NSURLSession sharedSession] dataTaskWithURL:[NSURL URLWithString:url] completionHandler:^(NSData \* _Nullable data, NSURLResponse \* _Nullable response, NSError \* _Nullable error) {
        //Failed
        if (error) {
            return;
        }
        NSDictionary *result = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingAllowFragments error:nil];
        if (![result isKindOfClass:[NSDictionary class]]) {
            return;
        }
        result = result[self.selectedStore.storeNumber];
        NSMutableDictionary *mutableResult = result.mutableCopy;
        [result enumerateKeysAndObjectsUsingBlock:^(id  _Nonnull key, id  _Nonnull value, BOOL \* _Nonnull stop) {
            if (![value isKindOfClass:[NSString class]]) {
                [mutableResult removeObjectForKey:key];
            } else {
                if (self.onlyAvailabilityButton.state) {
                    if ([value isEqualToString:@"NONE"]) {
                        [mutableResult removeObjectForKey:key];
                    }
                }
            }
        }];
        result = mutableResult.copy;
        //Succeeded
        dispatch_async(dispatch_get_main_queue(), ^{
            self.availabilityDictionary = result;
            [self.availabilityTableView reloadData];
        });
    }];
    [task resume];
}

And the compressed project which I had removed sorts of heavy burden like YTKNetwork so as to complete the functionality of remote query without cocoapods:
[AppleReserver-master.zip](https://github.com/Sunnyyoung/AppleReserver/files/500762/AppleReserver-master.zip)

In any case, thanks for you artwork.

**Comment by sunnyyoung** [comment]
@ljysdfz 👍🏻 Well done!
