### ISSUE TITLE
请求加入多门店监控和兼容iPhone 12 Pro Max/Mini

### ISSUE THREAD

**Issue by lirunext** [Sunnyyoung/AppleReserver#22]
如题，请求加入多门店监控和兼容iPhone 12 Pro Max/Mini。
对于粉丝来说，在省内有多家官方店的情况下，当然是越早买到的重要性大于在某个门店买。所以多门店监控很有必要，对比过了，某天深圳益田店放了一批货，广州却没有，这种情况下，如果只能监控广州某家店，那么就不知道深圳放货了。

**Comment by lingaoyi** [comment]
确实没有Pro Max

**Comment by ChenAnTeng** [comment]
> 确实没有Pro Max

修改Products.json就可以了

**Comment by lingaoyi** [comment]
> > 确实没有Pro Max
> 
> 修改Products.json就可以了

老大，求教程。。。。

**Comment by ChenAnTeng** [comment]
> > > 确实没有Pro Max
> > 
> > 
> > 修改Products.json就可以了
> 
> 老大，求教程。。。。

Products.json内容替换
Constant.swift里链接
https://reserve-prime.apple.com/CN/zh_CN/reserve/A/stores.json
A改成G


[
    {
                "partNumber": "MGC53CH/A",
                "description": "iPhone 12 Pro Max 256GB 银色",
                "color": "银色",
                "capacity": "256GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 10,099",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-silver-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-silver-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGCA3CH\/A",
                "description": "iPhone 12 Pro Max 512GB 银色",
                "color": "银色",
                "capacity": "512GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 11,899",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-silver-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-silver-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGC63CH\/A",
                "description": "iPhone 12 Pro Max 256GB 金色",
                "color": "金色",
                "capacity": "256GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 10,099",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-gold-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620621000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-gold-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620621000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGCE3CH\/A",
                "description": "iPhone 12 Pro Max 512GB 海蓝色",
                "color": "海蓝色",
                "capacity": "512GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 11,899",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-blue-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620620000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-blue-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620620000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGC33CH\/A",
                "description": "iPhone 12 Pro Max 128GB 海蓝色",
                "color": "海蓝色",
                "capacity": "128GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 9,299",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-blue-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620620000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-blue-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620620000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGC13CH\/A",
                "description": "iPhone 12 Pro Max 128GB 银色",
                "color": "银色",
                "capacity": "128GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 9,299",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-silver-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-silver-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGCC3CH\/A",
                "description": "iPhone 12 Pro Max 512GB 金色",
                "color": "金色",
                "capacity": "512GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 11,899",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-gold-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620621000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-gold-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620621000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGC43CH\/A",
                "description": "iPhone 12 Pro Max 256GB 石墨色",
                "color": "石墨色",
                "capacity": "256GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 10,099",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-graphite-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-graphite-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGC93CH\/A",
                "description": "iPhone 12 Pro Max 512GB 石墨色",
                "color": "石墨色",
                "capacity": "512GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 11,899",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-graphite-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-graphite-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGC03CH\/A",
                "description": "iPhone 12 Pro Max 128GB 石墨色",
                "color": "石墨色",
                "capacity": "128GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 9,299",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-graphite-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-graphite-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620623000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGC23CH\/A",
                "description": "iPhone 12 Pro Max 128GB 金色",
                "color": "金色",
                "capacity": "128GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 9,299",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-gold-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620621000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-gold-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620621000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
            {
                "partNumber": "MGC73CH\/A",
                "description": "iPhone 12 Pro Max 256GB 海蓝色",
                "color": "海蓝色",
                "capacity": "256GB",
                "screenSize": "6.7 英寸显示屏",
                "price": "RMB 9,299",
                "installmentPrice": "",
                "installmentPeriod": "0",
                "paymentPrice": "",
                "paymentInstallments": "",
                "iUPPrice": "",
                "iUPInstallments": "2",
                "colorSortOrder": "",
                "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-blue-hero_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620620000",
                "image": "https:\/\/store.storeimages.cdn-apple.com\/8756\/as-images.apple.com\/is\/iphone-12-pro-max-blue-hero?wid=300&hei=300&fmt=jpeg&qlt=80&op_usm=0.5,0.5&.v=1601620620000",
                "contractEnabled": true,
                "unlockedEnabled": true,
                "groupID": "646118278",
                "groupName": "iPhone12",
                "subfamilyID": "700527277",
                "subfamily": "iPhone 12 Pro Max"
            },
]

**Comment by lingaoyi** [comment]
> Constant.swift里链接

Constant.swift 在哪来的？

**Comment by ChenAnTeng** [comment]
> > Constant.swift里链接
> 
> Constant.swift 在哪来的？

master - AppleReserver-Constant

官网链接现在 A是 12 Pro
G是 12 Pro Max

**Comment by feon019** [comment]
有沒有方法新增香港的店 用來作監控之用

**Comment by sunnyyoung** [comment]
https://github.com/Sunnyyoung/AppleReserver/releases/tag/5.0
