### ISSUE TITLE
怎么运行啊

### ISSUE THREAD

**Issue by liurenjin** [Sunnyyoung/AppleReserver#24]
5.0 下载后mac上怎么运行呢，不是gui的dmg程序？没找到运行方法。请教下

**Comment by TrayBer** [comment]
是不是打包没有正确保留文件后缀？
尝试改了 .zip 和 .app 后缀，都不行……

**Comment by sunnyyoung** [comment]
这是命令行应用，没有 GUI，需要通过终端运行
