### ISSUE TITLE
执行命令崩溃

### ISSUE THREAD

**Issue by fisher158163** [Sunnyyoung/AppleReserver#30]
执行`applereserver stores`命令发生崩溃，如下图：
<img width="1249" alt="截屏2023-02-04 11 28 10" src="https://user-images.githubusercontent.com/18113334/216745834-01e71aec-ec9b-4ea6-a1b5-973d1f287ad2.png">

**Comment by sunnyyoung** [comment]
当时是没开放在线预约，现在工作正常了。
