### ISSUE TITLE
store.json 接口已不可用

### ISSUE THREAD

**Issue by xiao99xiao** [Sunnyyoung/AppleReserver#5]
`https://reserve.cdn-apple.com/CN/zh_CN/reserve/iPhone/stores.json`
我这边测试这个接口已经只会返回

```
{
  "supportedDomains" : {
    "0" : "https://www.apple.com/jp/iphone-7/",
    "1" : "http://www.apple.com/",
    "2" : "http://storeint.apple.com/",
    "3" : "http://epp.apple.com/",
    "4" : "applestore://"
  },
  "appStatus" : "comeBackLater"
}
```

建议改成该接口
`http://www.apple.com/autopush/cn/retail/storelist/stores.xml`

**Comment by sunnyyoung** [comment]
@xiao99xiao 晚上10点到次日早上8点都是关闭预约状态的，这个正常。🌚

**Comment by xiao99xiao** [comment]
@Sunnyyoung 明白了。我其实是自己改成日本区（JP/ja_JP）在用，日本区的预约状态关闭时间段貌似比中国短。
