### ISSUE TITLE
增加澳门 Apple Store 的监控.

### ISSUE THREAD

**Issue by Fezreal** [Sunnyyoung/AppleReserver#7]
澳门新开了一家直营店.

**Comment by sunnyyoung** [comment]
@Fezreal 
目前只有用到大陆直营店接口
后面会加上全球直营店接口

**Comment by sunnyyoung** [comment]
https://github.com/Sunnyyoung/AppleReserver/commit/6201ab388af37f56471fb03a1190d03cdc58f7d5
