### ISSUE TITLE
你好，请求到的全都是无货?

### ISSUE THREAD

**Issue by tuxi** [Sunnyyoung/AppleReserver#8]
你好，
我fork了AppleReserver，使用它测试时，一直显示的都是无货，请问我需要配置什么吗？

**Comment by sunnyyoung** [comment]
@Ossey 因为Apple关闭了预约入口了，无需预约

**Comment by tuxi** [comment]
好的，谢谢啦，那您知道Apple一般什么时候还会开放预约入口吗？

**Comment by sunnyyoung** [comment]
@Ossey iPhone X 发布后的一周左右应该会开放，现在 iPhone8 货源充足，因此无需预约。

**Comment by tuxi** [comment]
我明白啦，非常感谢！
